// frontend-v2/app/routes/multiplayer/index.tsx
import { useSelector, useDispatch } from "react-redux";
import { useState, useEffect } from "react";
import { gameEngine } from "~/lib/game-engine";
import { io, type Socket } from "socket.io-client";
import type { GameEngine } from "~/lib/game-engine/types";
import type { AppDispatch, RootState } from "~/lib/store";
import { multiplayerGameSlice } from "~/lib/store";

export default function Multiplayer() {
  const dispatch = useDispatch<AppDispatch>();
  const gameState = useSelector((state: RootState) => state.multiplayerGame);
  const [socket] = useState<Socket>(() =>
    io(import.meta.env.VITE_BACKEND_URL || "http://localhost:8080")
  );
  const [idInput, setIdInput] = useState("");

  const blueMask: number = 0x0000ff;
  const timePerTurn: number = 500;

  // Handle side effects when certain actions are dispatched
  useEffect(() => {
    if (gameState.status === "gameOver") {
      const timeoutId = setTimeout(() => {
        dispatch(multiplayerGameSlice.actions.update_status("lookForAGame"));
      }, 3000);
      return () => clearTimeout(timeoutId);
    }
  }, [gameState.status, dispatch]);

  // Handle game engine side effects - emit updates to backend
  useEffect(() => {
    if (
      gameState.my_game &&
      gameState.roomId &&
      (gameState.my_game as any)._needsUpdate
    ) {
      const cleanGame = { ...gameState.my_game };
      delete (cleanGame as any)._needsUpdate;
      socket.emit("updateGameEngine", gameState.roomId, cleanGame);
    }
  }, [gameState.my_game, gameState.roomId, socket]);

  // Socket event listeners
  useEffect(() => {
    const handleRoomUpdate = (roomData: {
      id: string;
      players: GameEngine[] | undefined;
      limit: number;
      status: string;
    }) => {
      if (gameState.status === "gameOver") return;

      if (roomData.status === "gameStart") {
        dispatch(
          multiplayerGameSlice.actions.update_room({
            id: roomData.id,
            players: roomData.players,
            limit: roomData.limit,
            status: "in_game",
          })
        );
        start_loop();
      } else {
        dispatch(multiplayerGameSlice.actions.update_room(roomData));
      }
    };

    const handleUnknownRoomId = (message: string) => {
      console.error("Unknown room ID:", message);
      // Reset to initial state
      dispatch(multiplayerGameSlice.actions.update_status("lookForAGame"));
    };

    const handleExistingRoom = (message: string) => {
      console.error("Room already exists:", message);
      // Could show a message to user or auto-join
    };

    const handleFullRoom = (message: string) => {
      console.error("Room is full:", message);
      dispatch(multiplayerGameSlice.actions.update_status("lookForAGame"));
    };

    const handleNewPiece = (piece: any) => {
      if (gameState.my_game?.current_piece === undefined) {
        dispatch(multiplayerGameSlice.actions.newPiece(piece));
      }
    };

    const handleGameOver = () => {
      dispatch(multiplayerGameSlice.actions.update_status("gameOver"));
    };

    const handleAddUndestructableLine = (lineCount: number) => {
      dispatch(multiplayerGameSlice.actions.add_undestructable_line(lineCount));
    };

    // Register event listeners
    socket.on("roomUpdate", handleRoomUpdate);
    socket.on("unknownRoomId", handleUnknownRoomId);
    socket.on("existingRoom", handleExistingRoom);
    socket.on("fullRoom", handleFullRoom);
    socket.on("newPiece", handleNewPiece);
    socket.on("gameOver", handleGameOver);
    socket.on("add_undestructable_line", handleAddUndestructableLine);

    // Cleanup event listeners on unmount
    return () => {
      socket.off("roomUpdate", handleRoomUpdate);
      socket.off("unknownRoomId", handleUnknownRoomId);
      socket.off("existingRoom", handleExistingRoom);
      socket.off("fullRoom", handleFullRoom);
      socket.off("newPiece", handleNewPiece);
      socket.off("gameOver", handleGameOver);
      socket.off("add_undestructable_line", handleAddUndestructableLine);
    };
  }, [socket, dispatch, gameState.status, gameState.my_game?.current_piece]);

  // Auto-start game loop when game begins and we have a piece
  useEffect(() => {
    if (gameState.status === "gameStart" && gameState.my_game?.current_piece) {
      console.log(
        "Starting game loop - status:",
        gameState.status,
        "has piece:",
        !!gameState.my_game?.current_piece
      );
      start_loop();
    } else if (
      gameState.status !== "gameStart" &&
      gameState.intervalId !== null
    ) {
      console.log("Stopping game loop - status:", gameState.status);
      dispatch(multiplayerGameSlice.actions.clear_intervalId());
    }
  }, [gameState.status, gameState.my_game?.current_piece, dispatch]);

  const getCellColor = (num: number, mask: number = 0xffffff): string => {
    return num !== 0
      ? num === gameEngine.undestructable_line_color
        ? "#" + num.toString(16).padStart(6, "0")
        : (num & mask) === 0
        ? "#0000b0"
        : "#" + (num & mask).toString(16).padStart(6, "0")
      : "#000000";
  };

  const joinARoom = (id: string) => {
    console.log("Joining room with ID:", id);
    socket.emit("joinRoom", id);
    dispatch(multiplayerGameSlice.actions.update_room_id(id));
  };

  const createARoom = (id: string) => {
    console.log("Creating room with ID:", id);
    socket.emit("createRoom", id);
    dispatch(multiplayerGameSlice.actions.update_room_id(id));
  };

  const startGame = () => {
    if (gameState.opp_game !== undefined && gameState.opp_game.length > 0) {
      socket.emit("startGame", {
        roomId: gameState.roomId,
        my_game: gameState.my_game,
      });
    }
  };

  const leaveRoom = () => {
    if (gameState.roomId) {
      socket.emit("leaveRoom", gameState.roomId);
      dispatch(multiplayerGameSlice.actions.update_status("lookForAGame"));
      dispatch(multiplayerGameSlice.actions.update_room_id(""));
    }
  };

  const lookForAGame = () => {
    dispatch(multiplayerGameSlice.actions.update_status("lookingForAGame"));
    const interval = setInterval(() => {
      dispatch(multiplayerGameSlice.actions.update_lookingForAGame());
    }, 500);
    dispatch(multiplayerGameSlice.actions.set_intervalId(interval));
  };

  const start_loop = () => {
    // Clear any existing interval first
    if (gameState.intervalId !== null) {
      clearInterval(gameState.intervalId);
    }

    const game_loop = () => {
      if (
        gameState.my_game?.current_piece === undefined ||
        gameState.my_game!.game_over
      ) {
        return;
      }
      dispatch(multiplayerGameSlice.actions.translate_piece_down());
    };
    const intervalId = setInterval(game_loop, timePerTurn);
    dispatch(multiplayerGameSlice.actions.set_intervalId(intervalId));
  };

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      const activeElement = document.activeElement as HTMLElement;
      if (
        activeElement &&
        (activeElement.tagName === "INPUT" ||
          activeElement.tagName === "TEXTAREA")
      ) {
        return;
      }

      if (
        gameState.my_game !== undefined &&
        gameState.status === "gameStart" &&
        !gameState.my_game.game_over
      ) {
        switch (event.key) {
          case "ArrowDown":
            dispatch(multiplayerGameSlice.actions.translate_piece_down());
            break;
          case "ArrowUp":
            dispatch(multiplayerGameSlice.actions.rotate_piece());
            break;
          case "ArrowLeft":
            dispatch(multiplayerGameSlice.actions.translate_piece_side(-1));
            break;
          case "ArrowRight":
            dispatch(multiplayerGameSlice.actions.translate_piece_side(1));
            break;
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [dispatch, gameState.my_game, gameState.status]);

  return (
    <section className="flex flex-col justify-center items-center w-[70lvh] h-[50lvh] text-center">
      <div className="flex flex-row justify-center items-center w-full h-full">
        {gameState.status === "lookForAGame" && (
          <section className="flex flex-row gap-x-8">
            <button
              onClick={lookForAGame}
              className="w-[20lvh] flex flex-col hover:text-sky-200 hover:scale-110 transition-transform duration-100 cursor-pointer"
            >
              look for a game
            </button>
            <button
              onClick={() =>
                dispatch(
                  multiplayerGameSlice.actions.update_status("joinARoom")
                )
              }
              className="w-[20lvh] flex flex-col hover:text-sky-200 hover:scale-110 transition-transform duration-100 cursor-pointer"
            >
              join/create a room
            </button>
          </section>
        )}

        {gameState.status === "joinARoom" && (
          <div className="flex flex-col justify-center items-center gap-y-4">
            <input
              value={idInput}
              onChange={(e) => setIdInput(e.target.value)}
              className="w-full px-4 py-2 rounded-lg text-center border border-red-300 focus:outline-none focus:ring-2 focus:ring-sky-200 focus:border-transparent hover:placeholder:text-sky-200 shadow-sm hover:border-gray-400 disabled:bg-gray-100 disabled:text-gray-500 disabled:cursor-not-allowed"
              placeholder="enter room id"
            />
            <div className="flex flex-row gap-x-4">
              <button
                onClick={() => joinARoom(idInput)}
                disabled={!idInput.trim()}
                className="w-[10lvh] flex flex-col hover:text-sky-200 hover:scale-110 transition-transform duration-100 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              >
                join
              </button>
              <button
                onClick={() => createARoom(idInput)}
                disabled={!idInput.trim()}
                className="w-[10lvh] flex flex-col hover:text-sky-200 hover:scale-110 transition-transform duration-100 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              >
                create
              </button>
              <button
                onClick={() =>
                  dispatch(
                    multiplayerGameSlice.actions.update_status("lookForAGame")
                  )
                }
                className="w-[10lvh] flex flex-col hover:text-red-400 hover:scale-110 transition-transform duration-100 cursor-pointer"
              >
                back
              </button>
            </div>
          </div>
        )}

        {gameState.status === "lookingForAGame" && (
          <h1 className="w-[32lvh] flex flex-col hover:text-sky-200 cursor-progress">
            {gameState.lookingForAGame}
          </h1>
        )}

        {gameState.status === "gameRoom" && (
          <section className="flex flex-col items-center justify-center gap-y-4">
            <h1 className="w-[32lvh] flex flex-col hover:text-sky-200 text-center">
              currently in game room with{" "}
              {(gameState.opp_game?.length || 0) + 1} total players (
              {gameState.opp_game?.length || 0} opponents)
            </h1>
            <div className="flex flex-row gap-x-4">
              <button
                onClick={startGame}
                disabled={
                  !gameState.opp_game || gameState.opp_game.length === 0
                }
                className="w-[20lvh] flex flex-col hover:text-sky-200 hover:scale-110 transition-transform duration-100 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              >
                start game
              </button>
              <button
                onClick={leaveRoom}
                className="w-[20lvh] flex flex-col hover:text-red-400 hover:scale-110 transition-transform duration-100 cursor-pointer"
              >
                leave room
              </button>
            </div>
          </section>
        )}

        {gameState.status === "gameStart" && (
          <div className="w-full h-full flex items-center justify-center p-4">
            <section className="flex flex-row justify-between gap-x-6 h-full max-h-full items-center">
              <div className="flex flex-col gap-y-2 items-center">
                <h1 className="text-lg font-bold text-red-200">You</h1>
                <div className="flex items-center justify-center">
                  <div
                    className="grid gap-0.5"
                    style={{
                      gridTemplateColumns: `repeat(${
                        gameState.my_game!.current_board[0].length
                      }, 1fr)`,
                      gridTemplateRows: `repeat(${
                        gameState.my_game!.current_board.length
                      }, 1fr)`,
                      height: "min(calc(100vh - 20rem), 500px)",
                      aspectRatio: `${
                        gameState.my_game!.current_board[0].length
                      } / ${gameState.my_game!.current_board.length}`,
                    }}
                  >
                    {gameEngine
                      .add_current_piece_to_board(gameState.my_game!)
                      .current_board.flat()
                      .map((num, index) => (
                        <div
                          key={index}
                          className="rounded-sm border border-red-900/30"
                          style={{
                            backgroundColor: getCellColor(num),
                            minWidth: "12px",
                            minHeight: "12px",
                          }}
                        />
                      ))}
                  </div>
                </div>
              </div>

              <div className="flex flex-col gap-y-4 items-center max-h-full overflow-y-auto">
                <h1 className="text-lg font-bold text-blue-200">Opponents</h1>
                {gameState.opp_game?.map(
                  (opp: GameEngine, oppIndex: number) => (
                    <div
                      key={oppIndex}
                      className="flex flex-col items-center gap-y-2"
                    >
                      <span className="text-sm text-gray-400">
                        Player {oppIndex + 2}
                      </span>
                      <div
                        className="grid gap-0.5"
                        style={{
                          gridTemplateColumns: `repeat(${opp.current_board[0].length}, 1fr)`,
                          gridTemplateRows: `repeat(${opp.current_board.length}, 1fr)`,
                          height: "min(200px, 25vh)",
                          aspectRatio: `${opp.current_board[0].length} / ${opp.current_board.length}`,
                        }}
                      >
                        {opp.current_board
                          .flat()
                          .map((num: number, cellIndex: number) => (
                            <div
                              key={cellIndex}
                              className="rounded-sm"
                              style={{
                                backgroundColor: getCellColor(num, blueMask),
                                minWidth: "4px",
                                minHeight: "4px",
                              }}
                            />
                          ))}
                      </div>
                    </div>
                  )
                )}
              </div>
            </section>
          </div>
        )}

        {gameState.status === "gameOver" && (
          <h1 className="w-[32lvh] flex flex-col hover:text-sky-200 cursor-progress">
            {gameState.game_over_message}
          </h1>
        )}
      </div>
    </section>
  );
}

// frontend/src/app/multiplayer/multiplayer.component.ts
import { Component, HostListener, inject } from '@angular/core';
import { TetrisService } from '../tetris/tetris.service';
import { CommonModule } from '@angular/common';
import { Multiplayer } from './multiplayer';
import { createSlice } from '@reduxjs/toolkit'
import type { PayloadAction } from '@reduxjs/toolkit'
import { configureStore } from '@reduxjs/toolkit';
import { io, Socket } from 'socket.io-client';
import { GameEngine, Piece } from '../tetris/game-engine';

@Component({
  selector: 'app-multiplayer',
  imports: [CommonModule],
  templateUrl: './multiplayer.component.html',
  styleUrl: './multiplayer.component.css'
})
export class MultiplayerComponent {

  readonly tetrisService: TetrisService = inject(TetrisService);
  readonly multiplayer: Multiplayer = {
    my_game: this.tetrisService.newGameEngine(),
    opp_game: undefined,
    game_over: false,
    status: "lookForAGame",
    lookingForAGame: "looking for a game",
    roomId: "",
    roomLimit: 0,
    boardId: -1,
    previous_score: 0,
    game_over_message: "",
    intervalId: null,
  };
  readonly blueMask: number = 0x0000ff;
  readonly timePerTurn: number = 500;
  readonly socket: Socket = io("http://192.168.0.19:8080");
  readonly gameStateSlice = createSlice({
    name: 'gameState',
    initialState: this.multiplayer,
    reducers: {
      set_intervalId: (state, action: PayloadAction<ReturnType<typeof setInterval>>) => {
        state.intervalId = action.payload;
      },
      update_status: (state, action: PayloadAction<string>) => {
          state.status = action.payload;
          if (state.status === "gameOver") {
            if (state.intervalId !== null) clearInterval(state.intervalId);
            state.my_game!.game_over
              ? state.game_over_message = "you lost"
              : state.game_over_message = "you won"
            state.my_game = this.tetrisService.newGameEngine();
            state.boardId = -1;
            state.opp_game = undefined;
            state.roomId = "";
            state.roomLimit = 0;
            state.previous_score = 0;

            setTimeout(() => this.store.dispatch(this.gameStateSlice.actions.update_status("lookForAGame")), 3000);
          }
      },
      update_lookingForAGame: state => {
        state.lookingForAGame.length < 21
          ? state.lookingForAGame += "."
          : state.lookingForAGame = state.lookingForAGame.slice(0, state.lookingForAGame.length - 3)
      },
      update_room_id: (state, action: PayloadAction<string>) => {
        state.roomId = action.payload;
      },
      update_room: (state, action: PayloadAction<{ id: string, players: GameEngine[] | undefined, limit: number, status: string}>) => {
        if (state.boardId === -1 && action.payload.players !== undefined)
          state.boardId = action.payload.players.length - 1;
        if (action.payload.status === "in_game")
          state.status = "gameStart";
        else
          state.status = "gameRoom"
        state.opp_game = action.payload.players?.filter((_, i) => i !== state.boardId);
        state.roomLimit = action.payload.limit;
      },
      translate_piece_down: state => {
        if (state.my_game === undefined || state.my_game.current_piece === undefined) return;
        state.my_game = this.tetrisService.translate_piece_down(state.my_game);
        if (!this.tetrisService.can_exist(this.tetrisService.addRandomPiece(state.my_game))) {
          state.my_game.game_over = true;
          this.socket.emit("updateGameEngine", state.roomId, state.my_game);
          return;
        }
        if (state.my_game.current_piece === undefined) this.socket.emit("updateGameEngine", state.roomId, state.my_game);
      },
      rotate_piece: state => {
        if (state.my_game === undefined || state.my_game.current_piece === undefined) return;
        state.my_game = this.tetrisService.rotate_piece(state.my_game!);
      },
      translate_piece_side: (state, action: PayloadAction<number>) => {
        if (state.my_game === undefined || state.my_game.current_piece === undefined) return;
        state.my_game = this.tetrisService.translate_piece_side(state.my_game!, action.payload);
      },
      add_undestructable_line: (state, action: PayloadAction<number>) => {
        if (state.my_game === undefined || state.my_game.current_piece === undefined) return;
        state.my_game = this.tetrisService.add_undestructable_line(state.my_game, action.payload);
        if (!this.tetrisService.can_exist(this.tetrisService.add_current_piece_to_board(state.my_game))) {
          state.my_game.game_over = true;
          this.socket.emit("updateGameEngine", state.roomId, state.my_game);
        }
      },
      newPiece: (state, action: PayloadAction<Piece>) => {
        state.my_game!.current_piece = action.payload;
        if (!this.tetrisService.can_exist(this.tetrisService.add_current_piece_to_board(state.my_game!))) {
          state.my_game!.game_over = true;
          this.socket.emit("updateGameEngine", state.roomId, state.my_game);
        }
      },
    }
  });
  readonly store = configureStore({
    reducer: {
      gameState: this.gameStateSlice.reducer
    }
  })

  getCellColor(num: number, mask: number = 0xffffff): string {
    return num !== 0
      ? num === this.tetrisService.undestructable_line_color
        ? '#' + (num).toString(16).padStart(6, "0")
        : (num & mask) === 0
          ? '#0000b0'
          : '#' + (num & mask).toString(16).padStart(6, "0")
      : '#000000';
  }

  joinARoom(id: string) {
    this.socket.emit("joinRoom", id);
    this.store.dispatch(this.gameStateSlice.actions.update_room_id(id));
  }

  createARoom(id: string) {
    this.socket.emit("createRoom", id);
    this.store.dispatch(this.gameStateSlice.actions.update_room_id(id));
  }

  startGame() {
    const currentState = this.store.getState().gameState;
    if (currentState.opp_game !== undefined && currentState.opp_game.length > 0)
      this.socket.emit("startGame", { roomId: currentState.roomId, my_game: currentState.my_game });
  }

  lookForAGame() {
    const actions = this.gameStateSlice.actions;
    this.store.dispatch(actions.update_status("lookingForAGame"));
    let interval = setInterval(() => {
      this.store.dispatch(actions.update_lookingForAGame());
    }, 500);

    //setTimeout(() => {
    //  clearInterval(interval);
    //  this.multiplayer.my_game = this.tetrisService.newGameEngine();
    //  this.multiplayer.opp_game = this.tetrisService.newGameEngine();
    //  this.state = "game";
    //  this.start_loop();
    //}, 1000);
  }
  start_loop() {
    const actions = this.gameStateSlice.actions;
    const game_loop = () => {
      const currentState = this.store.getState().gameState;
      if (currentState.my_game?.current_piece === undefined || currentState.my_game!.game_over) {
        return;
      }
      this.store.dispatch(actions.translate_piece_down());
    }
    this.store.dispatch(actions.set_intervalId(setInterval(game_loop, this.timePerTurn)));
  }

  @HostListener('window:keydown', ['$event'])
  handleKeyDown(event: KeyboardEvent) {

    const activeElement = document.activeElement as HTMLElement;
    if (activeElement && (activeElement.tagName === 'INPUT' || activeElement.tagName === 'TEXTAREA')) {
      return;
    }

    const currentState = this.store.getState();
    const actions = this.gameStateSlice.actions;
    if (currentState.gameState.my_game !== undefined || (currentState.gameState.status != "play" && !currentState.gameState.my_game!.game_over))
      switch (event.key) {
        case 'ArrowDown':
          this.store.dispatch(actions.translate_piece_down());
          break;
        case 'ArrowUp':
          this.store.dispatch(actions.rotate_piece());
          break;
        case 'ArrowLeft':
          this.store.dispatch(actions.translate_piece_side(-1));
          break;
        case 'ArrowRight':
          this.store.dispatch(actions.translate_piece_side(1));
          break;
      }
  }

  constructor() {
    const actions = this.gameStateSlice.actions;
    this.socket.on("add_undestructable_line", (nb: number) => this.store.dispatch(actions.add_undestructable_line(nb)));
    this.socket.on("unknownRoomId", (msg: string) => alert(msg));
    this.socket.on("fullRoom", (msg: string) => alert(msg));
    this.socket.on("existingRoom", (msg: string) => alert(msg));
    this.socket.on("gameOver", () => this.store.dispatch(actions.update_status("gameOver")));
    this.socket.on("roomUpdate", ({
      id,
	    players,
	    limit,
      status,
    }) => {
      if (this.store.getState().gameState.status === "gameOver") return;
      if (status === "gameStart") {
        this.store.dispatch(actions.update_room({id, players, limit, status: "in_game"}));
        this.start_loop();
      }
      else {
        this.store.dispatch(actions.update_room({id, players, limit, status}));
      }
    });
    this.socket.on("newPiece", (piece: Piece) => {
      console.log(`newPiece: ${JSON.stringify(piece)}`);
      if (this.store.getState().gameState.my_game?.current_piece === undefined)
        this.store.dispatch(actions.newPiece(piece));
    });
  }

}

<section class="flex flex-row justify-center items-center w-[70lvh] h-[50lvh] text-center">
  <section
    *ngIf="store.getState().gameState.status === 'lookForAGame'"
    class="flex flex-row gap-x-8"
  >
    <button
      (click)="lookForAGame()"
      class="w-[20lvh] flex flex-col hover:text-sky-200 hover:scale-110 transition-transform duration-100 cursor-pointer"
    >
      look for a game
    </button>
    <button
      (click)="this.store.dispatch(this.gameStateSlice.actions.update_status('joinARoom'));"
      class="w-[20lvh] flex flex-col hover:text-sky-200 hover:scale-110 transition-transform duration-100 cursor-pointer"
    >
      join/create a room
    </button>
  </section>
  <div
    *ngIf="store.getState().gameState.status === 'joinARoom'"
    class="flex flex-col justify-center items-center gap-y-4">
      <input
        #idInput
        class="w-full px-4 py-2 rounded-lg
          text-center
          border border-red-300
          focus:outline-none focus:ring-2 focus:ring-sky-200 focus:border-transparent
          hover:placeholder:text-sky-200
          shadow-sm
          hover:border-gray-400
          disabled:bg-gray-100 disabled:text-gray-500 disabled:cursor-not-allowed"
        placeholder="enter room id"
      />
      <div
        class="flex flex-row gap-x-8"
      >
        <button
          (click)="joinARoom(idInput.value)"
          class="w-[10lvh] flex flex-col hover:text-sky-200 hover:scale-110 transition-transform duration-100 cursor-pointer"
        >
          join
        </button>
        <button
          (click)="createARoom(idInput.value)"
          class="w-[10lvh] flex flex-col hover:text-sky-200 hover:scale-110 transition-transform duration-100 cursor-pointer"
        >
          create
        </button>
      </div>
  </div>
  <h1
    *ngIf="store.getState().gameState.status === 'lookingForAGame'"
    class="w-[32lvh] flex flex-col hover:text-sky-200 cursor-progress"
  >
    {{this.store.getState().gameState.lookingForAGame}}
  </h1>
  <section
    *ngIf="store.getState().gameState.status === 'gameRoom'"
    class="flex flex-row items-center justify-center gap-x-5"
  >
    <h1 class="w-[32lvh] flex flex-col hover:text-sky-200">currently in game room with {{this.store.getState().gameState.opp_game!.length}} other players</h1>
      <button
        (click)="startGame()"
        class="w-[20lvh] flex flex-col hover:text-sky-200 hover:scale-110 transition-transform duration-100 cursor-pointer"
      >
        start game
      </button>
  </section>
  <section
    *ngIf="store.getState().gameState.status === 'gameStart'"
    class="flex flex-row items-center justify-center gap-x-5 pt-30"
  >

    <div class="flex flex-col gap-y-2 items-center">
      <h1 class="w-[32lvh] flex flex-col hover:text-sky-200">you</h1>
      <div class="grid gap-0"
           [ngClass]="'grid-cols-' + store.getState().gameState.my_game!.current_board[0].length">
        <div *ngFor="let num of (tetrisService.add_current_piece_to_board(store.getState().gameState.my_game!).current_board.flat())"
             class="w-4 h-4 sm:w-8 sm:h-8 rounded-lg"
             [style.backgroundColor]="getCellColor(num)">
        </div>
      </div>
    </div>
    <div class="flex flex-col gap-y-2 items-center">
      <h1 class="w-[32lvh] flex flex-col hover:text-sky-200">blue</h1>
      <div *ngFor="let opp of store.getState().gameState.opp_game!" class="flex flex-row flex-wrap justify-center items-center gap-2 max-h-[40lvh] max-w-[40lvh]">
        <div class="grid gap-0"
             [ngClass]="'grid-cols-' + opp.current_board[0].length">
          <div *ngFor="let num of opp.current_board.flat()"
               class="w-1 h-1 sm:w-2 sm:h-2 rounded-lg"
               [style.backgroundColor]="getCellColor(num, blueMask)">
          </div>
        </div>
      </div>
    </div>
  </section>
  <h1
    *ngIf="store.getState().gameState.status === 'gameOver'"
    class="w-[32lvh] flex flex-col hover:text-sky-200 cursor-progress"
  >
    {{this.store.getState().gameState.game_over_message}}
  </h1>
</section>
